# Generated by Django 4.2.16 on 2024-11-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='personalidade',
        ),
        migrations.AddField(
            model_name='animal',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='descrição'),
        ),
    ]
