# Generated by Django 5.1.2 on 2024-10-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='data_saida',
        ),
    ]
