# Generated by Django 5.1.2 on 2024-10-21 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_remove_clinica_data_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Logradouro')),
                ('numero_logradouro', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='numero_casa',
        ),
        migrations.AddField(
            model_name='tutor',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.endereco'),
        ),
    ]
