# Generated by Django 4.2.16 on 2024-12-04 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_queroadotar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querocachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Por que você quer adotar?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cachorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cachorro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Querogato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Por que você quer adotar?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.gato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Queroadotar',
        ),
    ]
