# Generated by Django 5.1.2 on 2024-10-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_endereco_remove_tutor_cep_remove_tutor_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereços'},
        ),
    ]
