# Generated by Django 4.2.16 on 2024-10-31 22:49

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_alter_endereco_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Imagem'),
        ),
    ]
